### PR TITLE
Refactorings.

### PR DESCRIPTION
**Pull request by PhilHudson**

### CODE REVIEW

**Comment by gdonald** [comment]
Your new version of `blackjack--load-saved-game` breaks `make test-coverage`.  It produces the error message "UNDERCOVER: No coverage information. Make sure that your files are not compiled?"

If you go here: https://github.com/undercover-el/undercover.el, and scroll all the way down, there are some trouble-shooting items listed.

**Comment by PhilHudson** [comment]
Sorry about that, I've reverted it. I'll have to read up that info, since I'm new to undercover too.

**Comment by gdonald** [comment]
Still getting `UNDERCOVER: No coverage information. Make sure that your files are not compiled?`.  Must be some other change too.

**Comment by gdonald** [comment]
Thank you.

**Pull request merged**
